########################
# Robot Specifications
########################
robot:
    pub_odom_tf: true
    odom_frame: "odom"
    base_frame: "base_link"
    cmd_vel_topic: "cmd_vel"
    wheel_radius: 0.155
    wheel_axle_length: 0.395
#############################
# Motor Drive Specifications
#############################
drive:
    serial_port: "/dev/ttyACM0"
    baud_rate: 115200
    open_loop: false
    #pulse-per-revolution for motor encoders
    encoder_ppr: 900
    #counts-per-revolution for motor encoders (ppr*4 for quadrature encoders)
    encoder_cpr: 3600
    max_amps: 30
    max_rpm: 3000

